//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relationship
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Accounts = new HashSet<Account>();
            this.ChildrenByFather = new HashSet<Person>();
            this.ChildernByMother = new HashSet<Person>();
        }
    
        public long Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<long> FatherId { get; set; }
        public Nullable<long> MotherId { get; set; }
        public string BirthDay { get; set; }
        public string BirthTime { get; set; }
        public string DeathDay { get; set; }
        public string DeathTime { get; set; }
        public string Remark { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedTime { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Person> ChildrenByFather { get; set; }
        public virtual Person Father { get; set; }
        public virtual ICollection<Person> ChildernByMother { get; set; }
        public virtual Person Mother { get; set; }
    }
}
