//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relationship
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.ChildrenByFather = new HashSet<Person>();
            this.ChildrenByMother = new HashSet<Person>();
        }
    
        public long Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public byte Gender { get; set; }
        public Nullable<long> FatherId { get; set; }
        public Nullable<long> MotherId { get; set; }
        public string BirthDay { get; set; }
        public string BirthTime { get; set; }
        public string DeathDay { get; set; }
        public string DeathTime { get; set; }
        public string Remark { get; set; }
        public long InsertedBy { get; set; }
        public System.DateTime InsertedTime { get; set; }
        public long UpdatedBy { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public Nullable<int> OrderInChildrenOfParents { get; set; }
    
        public virtual ICollection<Person> ChildrenByFather { get; set; }
        public virtual Person Father { get; set; }
        public virtual ICollection<Person> ChildrenByMother { get; set; }
        public virtual Person Mother { get; set; }
    }
}
